### PR TITLE
Remove commented restrictions because they are still in ReDoc

### PR DESCRIPTION
**Pull request by XaosSintez**

### CODE REVIEW

**Comment by 2e3s** [comment]
does this solve the problem for you locally?

**Comment by 2e3s** [comment]
well, it doesn't for me. Somehow it gets kept in `swagger.yaml`

**Comment by XaosSintez** [comment]
@2e3s we need to wait for tests. Then, preview will be available

**Comment by XaosSintez** [comment]
@2e3s 
http://rebilly.github.io/RebillyAPI/preview/remove-commented-restrictions/

They are removed now, check please

**Pull request merged**
