### PR TITLE
Rate limiting headers

### PR DESCRIPTION
**Pull request by XaosSintez**

### CODE REVIEW

**Comment by RomanGotsiy** [comment]
@XaosSintez, swagger don't have shared headers. You can reuse only whole responses.
You can't add `headers` key at the top level of swagger:

```
{
    "code": "OBJECT_ADDITIONAL_PROPERTIES",
    "message": "Additional properties not allowed: headers",
    "path": [] // <- empty path here means top level
  }```

**Comment by XaosSintez** [comment]
@RomanGotsiy yes, i already gor it :)
So, the only way is to add full headers description to each collection response?

**Comment by RomanGotsiy** [comment]
Yes

**Comment by slavcodev** [comment]
@XaosSintez You can add common response definition, and use `allOf` in paths.

**Comment by slavcodev** [comment]
@XaosSintez do you have in mind to add pagination headers in separate PR or you're missed that issue?

**Comment by XaosSintez** [comment]
@slavcodev yes, i remember, going to add them in another PR. This one is more about structure, how to make headers.

If you think this PR is good, let's merge it

**Comment by slavcodev** [comment]
OK, I was confuse by status in JIRA. Merged!

**Pull request merged**
