### PR TITLE
Make bank account status read-only

### PR DESCRIPTION
**Pull request by ashkarpetin**

### CODE REVIEW

**Comment by adamaltman** [comment]
How does someone deactivate a bank account?

**Comment by adamaltman** [comment]
@dara123 I don't understand how you can give this a checkmark given your experience with a particular use case.

**Comment by ashkarpetin** [comment]
@adamaltman You can create bank account and deactivate it

**Comment by adamaltman** [comment]
This won't work with a specific client integration that is already existing and in-use.

**Pull request closed without merging**
