### PR TITLE
Rules webhook action

### PR DESCRIPTION
**Pull request by slavcodev**
blocks #24

### CODE REVIEW

**Comment by creocoder** [comment]
Ideal payload as i see that:

```json
{
    "name": "Test webhook",
    "method": "POST",
    "url": "http://example.com",
    "query": {
        "param1": "value1",
        "param2": ["value2", "value3"],
    },
       "auth":  {
           "type": "foo",
           // custom fields there depends on type
       }
    "headers": {
        "name1": "value1",
        "name2": ["value2", "value3"],
    },
    "body": "some",
    "status": "active",
}
```

Only "name", "method" and "url" is required. Other fields are optional.

**Comment by slavcodev** [comment]
Screenshot

**Comment by slavcodev** [comment]
Please review, it is ready to merge now.

**Comment by adamaltman** [comment]
seems good to me :+1:

**Comment by slavcodev** [comment]
OK, I'm merging it at now, if any issues will appear, will fix separately.

**Pull request merged**
