### PR TITLE
Rules alternative version of conditions

### PR DESCRIPTION
**Pull request by slavcodev**
[Alternative version of conditions](https://github.com/Rebilly/RebillyAPI/pull/24): combined 4 definitions in one with additional property

### CODE REVIEW

**Comment by slavcodev** [comment]
screenshot

**Comment by XaosSintez** [comment]
If we are going to remove `lt`, `gt`, `ne` then :+1:

**Comment by slavcodev** [comment]
Yes, we do, `lt`, `gt` removed in this PR. But I'm ensure, is it not confused the attributes `operation` and `operator` in one object? e.q.

```json
{
   "criteria": {
     "operation": "compare",
     "operator": "=",
     "field": "customerId",
     "value": "abc",    
   }
}
```

**Comment by XaosSintez** [comment]
i think it is ok. But someone can disagree with me

**Comment by creocoder** [comment]
I think its OK. Not sure strict is necessary.

**Comment by slavcodev** [comment]
Well, as far as I see, PR declined.

**Pull request closed without merging**
