### PR TITLE
Alternative version of negate conditions

### PR DESCRIPTION
**Pull request by slavcodev**
[Alternative version of negate conditions](https://github.com/Rebilly/RebillyAPI/pull/24): remove definitions duplicates for negation and add logical "not" definition

### CODE REVIEW

**Comment by slavcodev** [comment]
Screenshot

**Comment by mdomba** [comment]
would it make sense to put "not" as first operator?

**Comment by slavcodev** [comment]
first where? in the operations lists in UI? I'm not sure how they sorted :)
@RomanGotsiy said me in `ReDoc` they are not sorting, in enum I wrote: `and`, `or`, `not`, but for some reason order is unclear :)

**Comment by adamaltman** [comment]
It's definitely alpha sort.  I was also going to say why isn't or next to and...

**Comment by adamaltman** [comment]
Can you use all operations with not?  So..

```
not => [
    and => [
        in => ['a', 'b', 'c'],
        less-than => 50,
    ]
]
```

**Comment by slavcodev** [comment]
> Can you use all operations with not?

Yes, any composition

**Comment by RomanGotsiy** [comment]
@slavcodev 
> @RomanGotsiy said me, that in ReDoc they are not sorting, in enum I wrote: and, or, not, but for some reason order is unclear seems alphabetical :)

I've checked once more and they are sorted, this is not intentionally. I'll fix this.

**Comment by slavcodev** [comment]
Accepted.

**Pull request merged**
